#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/config.toml" ]]; then
    cp "${APP_DIR}/config.toml" "${CONFIG_DIR}/config.toml"
    chown hotio:hotio "${CONFIG_DIR}/config.toml"
fi